In [1]:
!pip install joblib # saving file as a binary

In [2]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
plt.style.use("fivethirtyeight")

In [3]:
np.random.randn(3)

array([ 0.50025929, -0.33940635,  0.47618803])

In [14]:
y=-np.ones((4,1))
y

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [13]:
x=np.ones((4,2))
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
np.c_[x,y]

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])

In [17]:
class perceptron:
    def __init__(self,eta:float=None, epochs:int=None):
        self.weights=np.random.randn(3)*1e-4  # keeping initial weights very small by mulptiplying with 10 to the power4
        self.eta=eta  # Learning rates
        self.epochs=epochs # iterations.
    
    def fit(self,x,y):
        self.x=x
        self.y=y
        x_with_bias=np.c_[self.x,-np.ones((len(self.x),1))]
        print(f"x with biases: \n {x_with_bias}")
        

In [20]:
obj=perceptron(eta=0.01,epochs=10)
#print(perceptron.epochs,perceptron.eta,perceptron.weights)


In [23]:
obj.eta,obj.epochs,obj.weights

(0.01, 10, array([1.21895769e-04, 3.20298212e-05, 7.59849560e-06]))

In [25]:
obj.fit(x,y)

x with biases 
 [[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
