In [1]:
!pip install joblib # saving file as a binary

In [26]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd
plt.style.use("fivethirtyeight")

In [3]:
np.random.randn(3)

array([ 0.50025929, -0.33940635,  0.47618803])

In [14]:
y=-np.ones((4,1))
y

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [13]:
x=np.ones((4,2))
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
np.c_[x,y]

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])

In [52]:
class perceptron:
    def __init__(self,eta:float=None, epochs:int=None):
        self.weights=np.random.randn(3)*1e-4  # keeping initial weights very small by mulptiplying with 10 to the power4
        self.eta=eta  # Learning rates
        self.epochs=epochs # iterations.
        
    def _z_outcome(self,inputs,weights):
        return np.dot(inputs,weights)
    
    def activation(self,z):
        return np.where(z>0,1,0)
    
    def fit(self,x,y):
        self.x=x
        self.y=y
        x_with_bias=np.c_[self.x,-np.ones((len(self.x),1))]
        print(f"x with biases: \n {x_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch>>{epoch+1}")
            print("--"*10)
            z=self._z_outcome(x_with_bias,self.weights)
            #print(f"forwardpass: \n {z}")
            y_hat=self.activation(z)
            print(f"prediction after forward pass:\n{y_hat}")
            self.error=self.y-y_hat
            print(f"errors after forward pass:\n{self.error}")
            self.weights=self.weights+self.eta*np.dot(x_with_bias.T,self.error)
            print(f"new updated weights after {epoch+1}/{self.epochs}:\n{self.weights}")
    def prediction(self,x):
        x_with_bias=np.c_[self.x,-np.ones((len(self.x),1))]
        z=self._z_outcome(x_with_bias,self.weights)
        return self.activation(z)
    
        
    

In [53]:
OR={
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,1,1,1]
}

df_or=pd.DataFrame(OR)
df_or

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [54]:
def prepare_data(df,target_col="y"):
    x=df.drop(target_col,axis=1)
    y=df[target_col]
    return x,y

In [55]:
x,y=prepare_data(df_or)
eta=0.1
epochs=10
model_or=perceptron(eta=eta,epochs=epochs)
model_or.fit(x,y)

x with biases: 
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch>>1
--------------------
prediction after forward pass:
[0 0 1 0]
errors after forward pass:
0    0
1    1
2    0
3    1
Name: y, dtype: int64
new updated weights after 1/10:
[ 0.10001534  0.19997898 -0.1999879 ]
--------------------
for epoch>>2
--------------------
prediction after forward pass:
[1 1 1 1]
errors after forward pass:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
new updated weights after 2/10:
[ 0.10001534  0.19997898 -0.0999879 ]
--------------------
for epoch>>3
--------------------
prediction after forward pass:
[1 1 1 1]
errors after forward pass:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
new updated weights after 3/10:
[1.00015336e-01 1.99978979e-01 1.21001019e-05]
--------------------
for epoch>>4
--------------------
prediction after forward pass:
[0 1 1 1]
errors after forward pass:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
new updated

In [51]:
model_or.prediction(x)

array([0, 1, 1, 1])

In [20]:
obj=perceptron(eta=0.01,epochs=10)
#print(perceptron.epochs,perceptron.eta,perceptron.weights)


In [23]:
obj.eta,obj.epochs,obj.weights

(0.01, 10, array([1.21895769e-04, 3.20298212e-05, 7.59849560e-06]))

In [25]:
obj.fit(x,y)

x with biases 
 [[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
